[build]
  command = "npm run build"
  functions = ".next/server"
  publish = ".next/static"

[functions]
  nodejs_version = "20"
  included_files = [".next/server/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
