[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[functions]
  nodejs_version = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
